import Head from "next/head";
import AboutSection from "~/components/AboutSection";
import TestimonialSection from "~/components/TestimonialSection";
import AboutHeader from "~/components/AboutHeader";

export default function About() {

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <>
                    <AboutHeader/>
                <AboutSection/>
                    <TestimonialSection/>
                </>

            </main>
        </>
    );
}

