import Head from "next/head";
import BiblioHeader from "~/components/BiblioHeader";
import BooksSection from "~/components/BooksSection";

export default function Biblio() {

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <>
                <BiblioHeader/>
                    <BooksSection/>
                </>

            </main>
        </>
    );
}

