import Head from "next/head";
import MyCarousel from "~/components/MyCarousel";
import AboutSection from "~/components/AboutSection";
import CategorySection from "~/components/CategorySection";
import TeamSection from "~/components/TeamSection";
import TestimonialSection from "~/components/TestimonialSection";
import ContactSection from "~/components/ContactSection";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
            <MyCarousel/>
            <AboutSection/>
            <CategorySection/>
            <TeamSection/>
            <TestimonialSection/>
            <ContactSection/>
        </>

      </main>
    </>
  );
}

